[workspace]
authors = ["MoSafi2 <mohamed.mabrouk@rwth-aachen.de>"]
channels = ["https://conda.modular.com/max-nightly", "conda-forge"]
name = "cairo-mojo"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
mojo = "==0.26.1.0"
